SSAnne_2F_Room5_MapScripts::
	.byte 0

SSAnne_2F_Room5_EventScript_Gentleman::
	msgbox SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
    .string "Você já foi à Zona de Safári na\n"
    .string "Cidade de Fuchsia?\p"
    .string "Há muitos tipos de Pokémon raros por lá.$"

SSAnne_2F_Room5_EventScript_LittleBoy::
	msgbox SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
    .string "Eu e meu vovô achamos a Zona de Safári\n"
    .string "incrível!\l"
    .string "Queria poder ir lá de novo.$"
