PewterCity_Museum_2F_MapScripts::
	.byte 0

PewterCity_Museum_2F_EventScript_Man::
	msgbox PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone, MSGBOX_NPC
	end

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
    .string "Pedra da Lua, é?\p"
    .string "O que ela tem de tão especial?\n"
    .string "Para mim parece uma pedra qualquer.$"

PewterCity_Museum_2F_EventScript_OldMan::
	msgbox PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding, MSGBOX_NPC
	end

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .string "20 de julho de 1969!\p"
    .string "A humanidade pisou na Lua pela\n"
    .string "primeira vez naquele dia.\p"
    .string "Comprei uma TV a cores só para poder\n"
    .string "assistir àquela notícia histórica!$"

PewterCity_Museum_2F_EventScript_Scientist::
	msgbox PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth, MSGBOX_NPC
	end

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .string "Este mês, estamos apresentando uma\n"
    .string "exposição espacial.$"

PewterCity_Museum_2F_EventScript_LittleGirl::
	msgbox PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu, MSGBOX_NPC
	end

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
    .string "Eu quero um Pikachu!\n"
    .string "Ele é tão fofinho!\p"
    .string "Eu pedi pro meu papai pegar um pra mim!$"

PewterCity_Museum_2F_EventScript_BaldingMan::
	msgbox PewterCity_Museum_1F_Text_PikachuSoonIPromise, MSGBOX_NPC
	end

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
    .string "Sim, um Pikachu em breve, eu prometo!$"

PewterCity_Museum_2F_EventScript_SpaceShuttle::
	msgbox PewterCity_Museum_1F_Text_SpaceShuttle, MSGBOX_SIGN
	end

PewterCity_Museum_1F_Text_SpaceShuttle::
    .string "Ônibus Espacial Columbia$"

PewterCity_Museum_2F_EventScript_MoonStone::
	msgbox PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon, MSGBOX_SIGN
	end

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
    .string "Um meteorito que caiu no Monte Moon.\n"
    .string "Acredita-se ser uma Pedra da Lua.$"

