gText_Birch_Welcome::
    .string "Olá a todos!\n"
    .string "Muito prazer em conhecê-lo!\p"
    .string "Boas-vindas ao mundo de Pokémon!\p"
    .string "Meu nome é Carvalho.\p"
    .string "As pessoas afetuosamente me chamam\n"
    .string "de Professor Pokémon.\p"
    .string "$"

gText_Birch_Pokemon::
	.string "Este mundo…\p"
	.string "$"

gText_Birch_MainSpeech::
    .string "…é amplamente habitado por criaturas\n"
    .string "chamadas Pokémon.\p"
    .string "Para algumas pessoas, Pokémon são amigos.\n"
    .string "Outros os usam em batalhas.\p"
    .string "Quanto a mim…\p"
    .string "Eu estudo os Pokémon como profissão.\p"
    .string "$"

gText_Birch_AndYouAre::
    .string "Mas antes, conte-me um pouco sobre\n"
    .string "você.\p$"

gText_Birch_BoyOrGirl::
	.string "Você é um menino?\n"
	.string "Ou é uma menina?$"

gText_Birch_WhatsYourName::
    .string "Vamos começar pelo seu nome.\n"
    .string "Como você se chama?$"

gText_Birch_SoItsPlayer::
    .string "Certo…\n"
    .string "Então seu nome é {PLAYER}.$"

gText_Birch_ThisIsYourRival::
    .string "Este é meu neto.\p"
    .string "Ele é seu rival desde que ambos\n"
    .string "eram bebês.\p"
    .string "…Hum, qual era o nome dele mesmo?$"

gText_Birch_ConfirmRivalName::
    .string "…Ah, era {RIVAL}?$"

gText_Birch_YourePlayer::
    .string "Isso mesmo! Agora eu me lembro!\n"
    .string "O nome dele é {RIVAL}!\p$"

gText_Birch_AreYouReady::
    .string "{PLAYER}!\p"
    .string "A sua própria lenda Pokémon está\n"
    .string "prestes a começar!\p"
    .string "Um mundo de sonhos e aventuras\n"
    .string "com Pokémon espera por você! Vamos lá!\p"
    .string "$"


