gText_ObtainedTheItem::
	.string "Obteve {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "A Mochila está cheia…$"

gText_PutItemInPocket::
	.string "{PLAYER} guardou {STR_VAR_2}\n"
	.string "no bolso {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} encontrou {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Que pena!\n"
	.string "A Mochila está cheia…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} guardou {STR_VAR_2}\n"
	.string "na Mochila.$"

gText_ObtainedTheDecor::
	.string "Obteve {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Que pena! Não há espaço para\n"
	.string "mais um {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} foi transferido\n"
	.string "para o PC.$"
