gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} foi enviado para\n"
	.string "o PC de Alguém.\p"
	.string "Foi colocado na\n"
	.string "Box “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} foi enviado para\n"
	.string "o PC do Bill.\p"
	.string "Foi colocado na\n"
	.string "Box “{STR_VAR_1}.”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "A Box “{STR_VAR_3}” no PC de\n"
	.string "Alguém estava cheia.\p"
	.string "{STR_VAR_2} foi enviado para\n"
	.string "a Box “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "A Box “{STR_VAR_3}” no\n"
	.string "PC do Bill estava cheia.\p"
	.string "{STR_VAR_2} foi enviado para\n"
	.string "a Box “{STR_VAR_1}.”$"

gText_NoMoreRoomForPokemon::
	.string "Não há mais espaço para Pokémon!\p"
	.string "As Boxes de Pokémon estão cheias e\n"
	.string "não podem aceitar mais nenhum!$"

gText_NicknameThisPokemon::
	.string "Deseja dar um apelido a\n"
	.string "este {STR_VAR_1}?$"
