	.align 2
gText_ConfirmSave::
	.string "Deseja salvar o jogo?$"

gText_AlreadySavedFile::
	.string "Já existe um arquivo salvo.\n"
	.string "Deseja sobrescrevê-lo?$"

gText_SavingDontTurnOff::
	.string "Salvando…\n"
	.string "Não desligue o console.$"

gText_PlayerSavedGame::
	.string "{PLAYER} salvou o jogo.$"

gText_DifferentSaveFile::
	.string "ATENÇÃO!\p"
	.string "Já existe um arquivo salvo diferente\n"
	.string "nesta memória.\p"
	.string "Se você salvar agora, a aventura anterior,\n"
	.string "incluindo itens e Pokémon,\l"
	.string "será totalmente perdida.\p"
	.string "Tem certeza de que deseja salvar agora\n"
	.string "e sobrescrever o arquivo anterior?$"

gText_SaveError::
	.string "Erro ao salvar.\p"
	.string "Por favor, verifique a\n"
	.string "memória de backup.$"

gText_SavingDontTurnOffPower::
	.string "Salvando…\n"
	.string "Não desligue o console.$"
