PewterCity_Mart_MapScripts::
	.byte 0

PewterCity_Mart_EventScript_Clerk::
	lock
	faceplayer
	message gText_HowMayIServeYou
	waitmessage
	pokemart PewterCity_Pokemart
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	release
	end

	.align 2
PewterCity_Pokemart::
	.2byte ITEM_POKE_BALL
	.2byte ITEM_NEST_BALL
	.2byte ITEM_POTION
	.2byte ITEM_ANTIDOTE
	.2byte ITEM_PARALYZE_HEAL
	.2byte ITEM_AWAKENING
	.2byte ITEM_BURN_HEAL
	.2byte ITEM_ESCAPE_ROPE
	.2byte ITEM_REPEL
	.2byte ITEM_NONE
	release
	end

PewterCity_Mart_EventScript_Youngster::
	msgbox PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy, MSGBOX_NPC
	end

PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
    .string "Um velho suspeito me enrolou e me fez\n"
    .string "comprar esse peixe Pokémon bizarro!\p"
    .string "Ele é totalmente fraco e me custou\n"
    .string "¥500!$"

PewterCity_Mart_EventScript_Boy::
	msgbox PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently, MSGBOX_NPC
	end

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
    .string "Boas surpresas acontecem se você\n"
    .string "treinar seus Pokémon com dedicação.\p"
    .string "Até mesmo os mais fracos podem te\n"
    .string "surpreender se você não desistir deles.$"
