ViridianForest_NorthEntrance_MapScripts::
	.byte 0

Route2_ViridianForest_NorthEntrance_EventScript_Youngster::
	msgbox Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests, MSGBOX_NPC
    end
	
Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Muitos Pokémon vivem apenas em\n"
    .string "florestas e cavernas.\p"
    .string "Você precisa ser persistente e\n"
    .string "procurar por toda parte para\l"
    .string "encontrar espécies diferentes.$"

Route2_ViridianForest_NorthEntrance_EventScript_OldMan::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "Você reparou nas arvorezinhas finas\n"
    .string "na beira da estrada?\p"
    .string "Elas podem ser cortadas com um golpe\n"
    .string "Pokémon especial, ouvi dizer.$"

Route2_ViridianForest_NorthEntrance_EventScript_CooltrainerF::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "Você conhece a técnica de cancelar\n"
    .string "a evolução?\p"
    .string "Quando um Pokémon estiver evoluindo,\n"
    .string "você pode interromper o processo.\p"
    .string "É uma técnica para criar seus Pokémon\n"
    .string "do jeitinho que eles são.$"
