SafariZone_West_RestHouse_MapScripts::
	.byte 0


SafariZone_West_RestHouse_EventScript_Man::
	msgbox SafariZone_West_Text_BaitMakesMonStickAround, MSGBOX_NPC
	end

SafariZone_West_Text_BaitMakesMonStickAround::
	.string "Eu não tenho nenhum {POKEBLOCK}, mas capturei\n"
	.string "uma boa quantidade de Pokémon.\p"
	.string "Você pode aumentar suas chances de captura\n"
	.string "se aproximando mais deles antes de\l"
	.string "lançar uma Bola Safári.$"

SafariZone_West_RestHouse_EventScript_Scientist::
	msgbox SafariZone_West_Text_RocksMakeMonRunButEasierCatch, MSGBOX_NPC
	end

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
	.string "Coloquei um {POKEBLOCK} no Alimentador.\n"
	.string "Mas parece que ele sumiu.\p"
	.string "Acho que algum Pokémon comeu sem\n"
	.string "eu nem perceber.$"


SafariZone_West_RestHouse_EventScript_CooltrainerF::
	msgbox SafariZone_West_Text_HikedLotsDidntSeeMonIWanted, MSGBOX_NPC
	end

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
    .string "Eu andei um montão, mas não vi nenhum\n"
    .string "dos Pokémon que eu queria.$"
