PewterCity_House2_MapScripts::
	.byte 0

PewterCity_House2_EventScript_OldMan::
	msgbox PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow, MSGBOX_NPC
	end

PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "Os Pokémon aprendem novas técnicas\n"
    .string "conforme vão crescendo.\p"
    .string "Mas alguns golpes precisam ser ensinados\n"
    .string "a eles pelas pessoas.$"

PewterCity_House2_EventScript_LittleBoy::
	msgbox PewterCity_House2_Text_MonsEasierCatchIfStatused, MSGBOX_NPC
	end

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "Fica muito mais fácil capturar um Pokémon\n"
    .string "se ele estiver com problema de status.\p"
    .string "Sono, veneno, queimadura ou paralisia…\n"
    .string "Todos esses são eficazes.\p"
    .string "Mas capturar um Pokémon nunca é uma\n"
    .string "certeza garantida!$"
