.set LOCALID_BILL_HUMAN,    1
.set LOCALID_BILL_CLEFAIRY, 2
.set LOCALID_PIKACHU, 3

@VAR_SEA_COTTAGE_STATE
@0 = Nothing yet. Runs Pikachu event if starter is in party
@1 = Checked for Pikachu event
@2 = Bill is in Teleporter
@3 = Rescued Bill
@4 = Got Badge 2, but didn't get DexNav. Only set by Misty, if you have Badge 2 when rescuing Bill, this is skipped.
@5 = Received the call to come to Bill's. Set in Cerulean, if you already had Badge 2 when rescuing Bill this is also skipped.
@6 = Got DexNav

Route25_SeaCottage_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route25_SeaCottage_OnTransition
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, Route25_SeaCottage_OnWarp
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Route25_SeaCottage_OnFrame
	.byte 0

Route25_SeaCottage_OnTransition::
	goto_if_ge VAR_SEA_COTTAGE_STATE, 3, Route25_SeaCottage_SetBillPosition
	end

Route25_SeaCottage_OnWarp:
	map_script_2 VAR_SEA_COTTAGE_STATE, 0, Route25_SeaCottage_CheckPartnerSceneSetups
	.2byte 0

Route25_SeaCottage_CheckPartnerSceneSetups::
	special IsPartnerInParty
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_End
	setflag FLAG_HIDE_FOLLOWER
	clearflag FLAG_HIDE_SEA_COTTAGE_PIKACHU
	addobject LOCALID_PIKACHU
	end

Route25_SeaCottage_SetBillPosition::
	setobjectxyperm LOCALID_BILL_HUMAN, 7,5
	end

Route25_SeaCottage_OnFrame:
	map_script_2 VAR_SEA_COTTAGE_STATE, 0, Route25_SeaCottage_PikachuLabScene
	.2byte 0

Route25_SeaCottage_PikachuLabScene::
	lock
	applymovement LOCALID_PIKACHU, Movement_PikachuScopesOutLab
	waitmovement 3
	playmoncry SPECIES_PIKACHU, CRY_MODE_NORMAL
	applymovement LOCALID_PIKACHU, Common_Movement_ExclamationMark
	waitmoncry
	applymovement LOCALID_PIKACHU, Movement_ReturnToPlayer
	waitmovement 3
	removeobject LOCALID_PIKACHU
	clearflag FLAG_HIDE_FOLLOWER
	setvar VAR_SEA_COTTAGE_STATE, 1
	release
	end

Movement_PikachuScopesOutLab::
	walk_up
	walk_up
	face_left
	delay_16
	face_right
	delay_16
	face_down
	emote_question_mark
	delay_16
	delay_16
	delay_16
	delay_16
	walk_right
	walk_right
	emote_question_mark
	delay_16
	delay_16
	walk_in_place_fast_right
	walk_in_place_fast_right
	delay_16
	walk_in_place_fast_right
	walk_in_place_fast_right
	delay_16
	walk_in_place_fast_right
	walk_in_place_fast_right
	delay_16
	walk_in_place_fast_right
	walk_in_place_fast_right
	step_end

Movement_ReturnToPlayer::
	walk_down
	walk_down
	walk_down
	walk_left
	walk_left
	step_end

Route25_SeaCottage_EventScript_Bill::
	lock
	faceplayer
	goto_if_set FLAG_EXHAUSTED_BILL, Route25_SeaCottage_EventScript_CollectionOrMega
	goto_if_set FLAG_FIRST_MEGASTONE, Route25_SeaCottage_EventScript_MegaStoneAcquired
	goto_if_set FLAG_SYS_DETECTOR_MODE, Route25_SeaCottage_EventScript_BillGoLookAtPC
	goto_if_set FLAG_SYS_DEXNAV_GET, Route25_SeaCottage_EventScript_CheckDexNavEvent
	goto_if_set FLAG_GOT_SS_TICKET, Route25_SeaCottage_EventScript_GetDexNavOrSmallTalk
	goto_if_set FLAG_HELPED_BILL_IN_SEA_COTTAGE, Route25_SeaCottage_EventScript_BillGiveSSTicket
	goto Route25_SeaCottage_EventScript_BillAskForHelp
	end

Route25_SeaCottage_EventScript_CheckDexNavEvent::
	goto_if_unset FLAG_BADGE05_GET, Route25_SeaCottage_EventScript_BillGoLookAtPC
	goto Route25_SeaCottage_EventScript_GetDexNavUpgrade
	end

Route25_SeaCottage_EventScript_BillAskForHelp::
	msgbox Route25_SeaCottage_Text_ImBillHelpMeOutPal, MSGBOX_YESNO
	call_if_eq VAR_RESULT, NO, Route25_SeaCottage_EventScript_DeclineHelpBill
	msgbox Route25_SeaCottage_Text_RunCellSeparationOnPC, MSGBOX_DEFAULT
	closemessage
	delay 10
	call_if_eq VAR_FACING, DIR_SOUTH, Route25_SeaCottage_EventScript_BillWalkToTeleporterSouth
	call_if_ne VAR_FACING, DIR_SOUTH, Route25_SeaCottage_EventScript_BillWalkToTeleporter
	opendoor 10, 3
	waitdooranim
	setflag FLAG_SAFE_FOLLOWER_MOVEMENT
	applymovement LOCALID_BILL_CLEFAIRY, Route25_SeaCottage_Movement_BillEnterTeleporter
	waitmovement 2
	clearflag FLAG_SAFE_FOLLOWER_MOVEMENT
	removeobject LOCALID_BILL_CLEFAIRY
	playse SE_CONTEST_CURTAIN_FALL
	closedoor 10, 3
	waitdooranim
	setflag FLAG_BILL_IN_TELEPORTER
	setvar VAR_SEA_COTTAGE_STATE, 2
	release
	end

Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "Opa! Eu sou um Pokémon…\n"
    .string "…Não, não sou!\p"
    .string "Me chame de Bill!\n"
    .string "Sou um PokéManíaco de verdade!\p"
    .string "Ei!\n"
    .string "Que cara de desconfiança é essa?\p"
    .string "Não estou brincando com você, amigo.\p"
    .string "Eu errei feio num experimento e fui\n"
    .string "fundido com um Pokémon!\p"
    .string "E então, o que acha?\n"
    .string "Me dá uma força aqui!$"

Route25_SeaCottage_EventScript_DeclineHelpBill::
	setflag FLAG_SAFE_FOLLOWER_MOVEMENT
	applymovement LOCALID_BILL_CLEFAIRY, Common_Movement_ExclamationMark
	clearflag FLAG_SAFE_FOLLOWER_MOVEMENT
	msgbox Route25_SeaCottage_Text_NoPlease, MSGBOX_DEFAULT
	return

Route25_SeaCottage_Text_NoPlease::
    .string "Não!?\n"
    .string "Não seja tão frio assim!\p"
    .string "Qual é, você precisa ajudar um cara\n"
    .string "em apuros gravíssimos!\p"
    .string "O que me diz?\n"
    .string "Por favor?\l"
    .string "Beleza?\l"
    .string "Tudo bem!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "Espere até eu entrar no\n"
    .string "teletransportador.\p"
    .string "Quando eu entrar, vá ao meu PC e rode\n"
    .string "o Sistema de Separação Celular.$"

Route25_SeaCottage_EventScript_BillWalkToTeleporterSouth::
	applymovement LOCALID_BILL_CLEFAIRY, Route25_SeaCottage_Movement_BillWalkToTeleporterSouth
	waitmovement 2
	return

Route25_SeaCottage_Movement_BillWalkToTeleporterSouth::
	walk_right
	walk_up
	walk_up
	walk_left
	walk_in_place_fast_up
	walk_in_place_fast_up
	step_end

Route25_SeaCottage_EventScript_BillWalkToTeleporter::
	applymovement LOCALID_BILL_CLEFAIRY, Route25_SeaCottage_Movement_BillWalkToTeleporter
	waitmovement 2
	return

Route25_SeaCottage_Movement_BillWalkToTeleporter::
	walk_up
	walk_up
	step_end

Route25_SeaCottage_Movement_BillEnterTeleporter::
	walk_up
	step_end

Route25_SeaCottage_EventScript_Computer::
	lockall
	goto_if_set FLAG_SYS_DEXNAV_GET, Route25_SeaCottage_EventScript_OpenBillsMonList
	goto_if_set FLAG_BILL_IN_TELEPORTER, Route25_SeaCottage_EventScript_RunCellSeparator
	msgbox Route25_SeaCottage_Text_TeleporterIsDisplayed
	releaseall
	end

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "Teleporter.exe está aberto na tela\n"
    .string "do monitor do computador.$"

Route25_SeaCottage_EventScript_RunCellSeparator::
	fadeoutbgm 0
	msgbox Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator
	closemessage
	clearflag FLAG_BILL_IN_TELEPORTER
	setvar VAR_SEA_COTTAGE_STATE, 3
	setflag FLAG_HELPED_BILL_IN_SEA_COTTAGE
	special SpawnCameraObject
	applymovement OBJ_EVENT_ID_CAMERA, Route25_SeaCottage_Movement_CameraPanToTeleporters
	waitmovement 0
	delay 35
	playse SE_PIN
	waitse
	setvar VAR_0x8004, 0
	special AnimateTeleporterHousing
	delay 10
	call Route25_SeaCottage_EventScript_PlayTeleporterBeepSE
	call Route25_SeaCottage_EventScript_PlayTeleporterBeepSE
	call Route25_SeaCottage_EventScript_PlayTeleporterBeepSE
	call Route25_SeaCottage_EventScript_PlayTeleporterBeepSE
	call Route25_SeaCottage_EventScript_PlayTeleporterBeepSE
	call Route25_SeaCottage_EventScript_PlayTeleporterBeepSE
	call Route25_SeaCottage_EventScript_PlayTeleporterBeepSE
	setvar VAR_0x8004, 1
	special AnimateTeleporterHousing
	playse SE_WARP_IN
	special AnimateTeleporterCable
	waitse
	call Route25_SeaCottage_EventScript_PlayTeleporterBeepSE
	call Route25_SeaCottage_EventScript_PlayTeleporterBeepSE
	call Route25_SeaCottage_EventScript_PlayTeleporterBeepSE
	call Route25_SeaCottage_EventScript_PlayTeleporterBeepSE
	call Route25_SeaCottage_EventScript_PlayTeleporterBeepSE
	opendoor 3, 3
	waitdooranim
	fadeinbgm 0
	addobject LOCALID_BILL_HUMAN
	clearflag FLAG_HIDE_SEA_COTTAGE_BILL
	delay 50
	playfanfare MUS_LEVEL_UP
	applymovement LOCALID_BILL_HUMAN, Route25_SeaCottage_Movement_BillExitTeleporter
	waitmovement 1
	waitfanfare
	applymovement OBJ_EVENT_ID_CAMERA, Route25_SeaCottage_Movement_CameraPanBackFromTeleporters
	waitmovement 0
	playse SE_CONTEST_CURTAIN_FALL
	closedoor 3, 3
	waitdooranim
	applymovement LOCALID_BILL_HUMAN, Route25_SeaCottage_Movement_BillWalkToMiddleOfRoom
	waitmovement 1
	special RemoveCameraObject
	releaseall
	end

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string "{PLAYER} abriu Teleporter.exe!\n"
    .string "Iniciou o Separador Celular.$"

Route25_SeaCottage_Movement_CameraPanToTeleporters::
	walk_up
	walk_up
	walk_right
	walk_right
	step_end

Route25_SeaCottage_EventScript_PlayTeleporterBeepSE::
	playse SE_BALL
	waitse
	delay 20
	return

Route25_SeaCottage_Movement_BillExitTeleporter::
	walk_down
	step_end

Route25_SeaCottage_Movement_CameraPanBackFromTeleporters::
	delay_16
	delay_16
	walk_down
	walk_down
	walk_left
	walk_left
	step_end

Route25_SeaCottage_Movement_BillWalkToMiddleOfRoom::
	walk_right
	walk_right
	walk_right
	walk_right
	walk_down
	walk_down
	step_end

Route25_SeaCottage_EventScript_BillGiveSSTicket::
	msgbox Route25_SeaCottage_Text_ThanksTakeThis, MSGBOX_DEFAULT
	checkitemspace ITEM_SS_TICKET, 1
	goto_if_eq VAR_RESULT, FALSE, Route25_SeaCottage_EventScript_NoRoomForSSTicket
	playfanfare MUS_RG_OBTAIN_KEY_ITEM
	message Route25_SeaCottage_Text_ReceivedSSTicketFromBill
	waitfanfare
	waitmessage
	additem ITEM_SS_TICKET, 1
	setflag FLAG_GOT_SS_TICKET
	setflag FLAG_SYS_PC_BILL
	closemessage
	goto Route25_SeaCottage_EventScript_CheckRegisterBill
	end

Route25_SeaCottage_Text_ThanksTakeThis::
    .string "Bill: Iuuu-huuu!\n"
    .string "Valeu, amigo! Te devo essa!\p"
    .string "Então, você veio ver a minha\n"
    .string "coleção de Pokémon?\p"
    .string "Não veio?\n"
    .string "Que pena.\p"
    .string "Mas preciso te agradecer…\n"
    .string "Ah, tome, talvez isto sirva.$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .string "{PLAYER} recebeu o Bilhete do\n"
    .string "S.S. Anne de Bill.$"

Route25_SeaCottage_EventScript_NoRoomForSSTicket::
	msgbox Route25_SeaCottage_Text_YouveGotTooMuchStuff
	release
	end
	
Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .string "Você está carregando coisas demais!$"


Route25_SeaCottage_EventScript_GetDexNavOrSmallTalk::
	goto_if_unset FLAG_SYS_DEXNAV_GET, Route25_SeaCottage_EventScript_CheckRegisterBill
	goto Route25_SeaCottage_EventScript_BillGoToSSAnne
	end

Route25_SeaCottage_EventScript_CheckRegisterBill::
	goto_if_set FLAG_BADGE02_GET, Route25_SeaCottage_EventScript_RegisterBill
	goto Route25_SeaCottage_EventScript_BillGoToSSAnne
	end

Route25_SeaCottage_EventScript_BillGoToSSAnne::
	msgbox Route25_SeaCottage_Text_SSAnnePartyYouGoInstead, MSGBOX_DEFAULT
	release
	end

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .string "Bill: Aquele navio de cruzeiro,\n"
    .string "o S.S. Anne, está em Vermilion.\p"
    .string "Ouvi dizer que há muitos treinadores\n"
    .string "a bordo também.\p"
    .string "Eles me convidaram para a festa deles,\n"
    .string "mas não suporto eventos chiques.\p"
    .string "Por que não vai no meu lugar?\n"
    .string "Vá lá e divirta-se bastante!$"

Route25_SeaCottage_EventScript_RegisterBill::
	msgbox Route25_SeaCottage_Text_ReallyOweYouOne, MSGBOX_DEFAULT
	applymovement LOCALID_BILL_HUMAN, Common_Movement_ExclamationMark
	waitmovement 1
	msgbox Route25_SeaCottage_Text_IsThatAPokedex, MSGBOX_DEFAULT
	playfanfare MUS_RG_OBTAIN_KEY_ITEM
	message Route25_SeaCottage_Text_GetDexNav
	waitfanfare
	waitmessage
	closemessage
	msgbox Route25_SeaCottage_Text_StillABeta, MSGBOX_DEFAULT
	setflag FLAG_SYS_DEXNAV_GET
	setvar VAR_SEA_COTTAGE_STATE, 6
	playfanfare MUS_REGISTER_MATCH_CALL
	message MatchCall_Text_RegisteredBill
	waitfanfare 
	waitmessage
	closemessage
	setflag FLAG_REGISTERED_BILL
	goto Route25_SeaCottage_EventScript_ExplainDexNav
	end
	
Route25_SeaCottage_Text_ReallyOweYouOne::
	.string "Bill: Sabe, eu realmente te devo uma\n"
	.string "por me salvar daquele acidente\l"
	.string "no teletransportador.\p"
	.string "Queria poder retribuir o favor\n"
	.string "com algo a mais além daquele\l"
	.string "Bilhete do S.S. Anne...$"

Route25_SeaCottage_Text_IsThatAPokedex::
	.string "Ah! Isso aí é uma Pokédex?\p"
	.string "O outro garoto que passou por aqui\n"
	.string "mais cedo também tinha uma.\p"
	.string "Você tem um PokéGear, né?\p"
	.string "Deixe-me instalar um aplicativo\n"
	.string "que andei desenvolvendo!$"

Route25_SeaCottage_Text_GetDexNav::
	.string "Bill adicionou o aplicativo DexNav\n"
	.string "ao PokéGear de {PLAYER}!$"

Route25_SeaCottage_Text_StillABeta::
	.string "Bill: Ele ainda está na fase Beta,\n"
	.string "tecnicamente falando.\p"
	.string "Tem mais alguns recursos que eu quero\n"
	.string "adicionar, mas isso pode levar um tempo.\p"
	.string "Já sei! Vou te passar o número do\n"
	.string "meu telefone celular.\p"
	.string "Assim você me avisa como o DexNav\n"
	.string "está funcionando, e eu te aviso se tiver\l"
	.string "novas atualizações!$"

Route25_SeaCottage_EventScript_ExplainDexNav::
	msgbox Route25_SeaCottage_Text_ExplainDexNav, MSGBOX_DEFAULT
	release
	end

Route25_SeaCottage_Text_ExplainDexNav::
	.string "Eu aprendi sobre a Pokédex trocando\n"
	.string "e-mails com o Prof. Carvalho!\p"
	.string "O DexNav deve tornar a busca por\n"
	.string "Pokémon raros muito mais interessante!\p"
	.string "Você pode rastrear vários tipos de\n"
	.string "Pokémon com ele, mas funciona melhor\l"
	.string "quando tem dados da Pokédex para aprender!\l"
	.string "Tente capturar muitos Pokémon!$"

Route25_SeaCottage_EventScript_DontLeaveMe::
	lock
	playse SE_WALL_HIT
	waitse
	playse SE_WALL_HIT
	waitse
	playse SE_WALL_HIT
	waitse
	msgbox Route25_SeaCottage_Text_DontLeaveMe, MSGBOX_DEFAULT
	applymovement OBJ_EVENT_ID_PLAYER, Movement_DontLeaveBills
	waitmovement 0
	release
	end

Route25_SeaCottage_Text_DontLeaveMe::
	.string "Bill: Ei! Você rodou o programa?\p"
	.string "Alô?\n"
	.string "Tem alguém aí!?\p"
	.string "Não me deixe preso aqui dentro!$"

Movement_DontLeaveBills:
	walk_up
	step_end


Route25_SeaCottage_EventScript_BillGoLookAtPC::
	msgbox Route25_SeaCottage_Text_CheckOutRareMonsOnPC, MSGBOX_NPC
	release
	end

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "Bill: Que tal dar uma olhada em alguns\n"
    .string "dos meus Pokémon raros no meu PC?\p"
    .string "Vá em frente, dê uma olhada no meu PC.$"

Route25_SeaCottage_EventScript_OpenBillsMonList::
	msgbox Route25_SeaCottage_Text_BillsFavoriteMonList
	goto Route25_SeaCottage_EventScript_BillsMonList
	end

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "Lista de Pokémon favoritos do Bill!$"

Route25_SeaCottage_EventScript_BillsMonList::
	message Route25_SeaCottage_Text_SeeWhichMon
	waitmessage
	multichoice 0, 0, MULTI_BILLS_POKEMON, FALSE
	switch VAR_RESULT
	case 0, Route25_SeaCottage_EventScript_ViewEevee
	case 1, Route25_SeaCottage_EventScript_ViewFlareon
	case 2, Route25_SeaCottage_EventScript_ViewJolteon
	case 3, Route25_SeaCottage_EventScript_ViewVaporeon
	case 4, Route25_SeaCottage_EventScript_ExitBillsMonList
	case MULTI_B_PRESSED, Route25_SeaCottage_EventScript_ExitBillsMonList
	end

Route25_SeaCottage_Text_SeeWhichMon::
    .string "Qual Pokémon você deseja ver?$"

Route25_SeaCottage_EventScript_ViewEevee::
	showmonpic SPECIES_EEVEE, 10, 3
	waitbuttonpress
	hidemonpic
	setvar VAR_0x8004, SPECIES_EEVEE
	special SetSeenMon
	goto Route25_SeaCottage_EventScript_BillsMonList
	end

Route25_SeaCottage_EventScript_ViewFlareon::
	showmonpic SPECIES_FLAREON, 10, 3
	waitbuttonpress
	hidemonpic
	setvar VAR_0x8004, SPECIES_FLAREON
	special SetSeenMon
	goto Route25_SeaCottage_EventScript_BillsMonList
	end

Route25_SeaCottage_EventScript_ViewJolteon::
	showmonpic SPECIES_JOLTEON, 10, 3
	waitbuttonpress
	hidemonpic
	setvar VAR_0x8004, SPECIES_JOLTEON
	special SetSeenMon
	goto Route25_SeaCottage_EventScript_BillsMonList
	end

Route25_SeaCottage_EventScript_ViewVaporeon::
	showmonpic SPECIES_VAPOREON, 10, 3
	waitbuttonpress
	hidemonpic
	setvar VAR_0x8004, SPECIES_VAPOREON
	special SetSeenMon
	goto Route25_SeaCottage_EventScript_BillsMonList
	end

Route25_SeaCottage_EventScript_ExitBillsMonList::
	releaseall
	end

Route25_SeaCottage_EventScript_GetDexNavUpgrade::
	msgbox Route25_SeaCottage_Text_HeyPlayerBeatGiovanni, MSGBOX_DEFAULT
	call_if_set FLAG_GAVE_BILL_IDEA, Route25_SeaCottage_EventScript_GaveBillIdea
	call_if_unset FLAG_GAVE_BILL_IDEA, Route25_SeaCottage_EventScript_BillHadIdea
	playfanfare MUS_RG_OBTAIN_KEY_ITEM
	message Route25_SeaCottage_Text_GetDetectorMode
	waitfanfare
	waitmessage
	closemessage
	msgbox Route25_SeaCottage_Text_DetectorMode, MSGBOX_DEFAULT
	setflag FLAG_SYS_DETECTOR_MODE
	release
	end

Route25_SeaCottage_Text_HeyPlayerBeatGiovanni::
	.string "Bill: Ei, {PLAYER}!\n"
	.string "Que bom que você veio.\p"
	.string "Estou vendo muita comoção sobre\n"
	.string "você na internet!\p"
	.string "Então, todos os boatos que li na\n"
	.string "rede são verdade?\p"
	.string "Você realmente derrotou o Líder\n"
	.string "da Equipe Rocket?\p"
	.string "Nossa. Isso é incrível.$"

Route25_SeaCottage_EventScript_GaveBillIdea::
	msgbox Route25_SeaCottage_Text_YourIdea, MSGBOX_DEFAULT
	return

Route25_SeaCottage_Text_YourIdea::
	.string "Que bom que você ligou mais cedo.\n"
	.string "Você me deu uma ótima ideia!\p"
	.string "Toda essa conversa sobre o Giovanni e a\n"
	.string "base secreta dele... me fez pensar sobre\l"
	.string "o que mais pode estar escondido por aí.\p"
	.string "Talvez existam Pokémon raros bem debaixo\n"
	.string "dos nossos narizes!\p"
	.string "Acho que essa melhoria vai nos ajudar\n"
	.string "a descobrir se eu estou certo!$"

Route25_SeaCottage_EventScript_BillHadIdea::
	msgbox Route25_SeaCottage_Text_MyIdea, MSGBOX_DEFAULT
	return

Route25_SeaCottage_Text_MyIdea::
	.string "Enfim, que bom que você veio.\n"
	.string "Estive trabalhando em melhorias para\l"
	.string "o DexNav.\p"
	.string "Acho que este upgrade será super útil!$"

Route25_SeaCottage_Text_GetDetectorMode::
	.string "Bill atualizou o seu DexNav!\n"
	.string "O Modo Detector foi ativado!$"

Route25_SeaCottage_Text_DetectorMode::
	.string "Bill: O Modo Detector ajuda a encontrar\n"
	.string "Pokémon ocultos por toda Kanto!\p"
	.string "Pokémon ocultos podem conhecer novos\n"
	.string "golpes ou ter habilidades raras.\p"
	.string "É realmente incrível!\n"
	.string "Vá lá experimentar!$"

Route25_SeaCottage_EventScript_MegaStoneAcquired::
	goto_if_unset FLAG_SYS_DETECTOR_MODE, Route25_SeaCottage_EventScript_GetDexNavUpgrade
	msgbox Route25_SeaCottage_Text_MegaStoneAcquired MSGBOX_DEFAULT
	waitmessage
	setflag FLAG_EXHAUSTED_BILL
	release
	end

Route25_SeaCottage_Text_MegaStoneAcquired:
	.string "Ei, {PLAYER}!\n"
	.string "Que bom que você veio.\p"
	.string "Então, você encontrou uma Mega Pedra!\p"
	.string "Descobri que se um Pokémon segurar a sua\n"
	.string "Mega Pedra em batalha, ele pode liberar\l"
	.string "uma força interior oculta,\l"
	.string "evoluindo temporariamente!\p"
	.string "Incrível, não é?\p"
	.string "Para testar isso em batalha, aperte o\n"
	.string "botão START enquanto seleciona o seu\l"
	.string "próximo golpe. O Mega Anel\l"
	.string "deverá brilhar!\p"
	.string "Vá em frente e experimente a\n"
	.string "Megaevolução, e não hesite em voltar\l"
	.string "se tiver qualquer dúvida.$"

Route25_SeaCottage_EventScript_CollectionOrMega::
	msgbox ROUTE25_SeaCottage_Text_CollectionOrMegaHelp MSGBOX_YESNO
	compare VAR_RESULT, 0
	goto_if_eq Route25_SeaCottage_EventScript_PlayerAnsweredNo
	msgbox Route25_SeaCottage_Text_MegaHelp, MSGBOX_DEFAULT
	release
	end

ROUTE25_SeaCottage_Text_CollectionOrMegaHelp:
	.string "Ei, você tem dúvidas sobre como usar\n"
	.string "o Mega Anel e as Mega Pedras?$"

Route25_SeaCottage_Text_MegaHelp:
	.string "Certo, sem problemas!\p"
	.string "Como deve ter reparado, o Mega Anel é um\n"
	.string "bracelete com uma gema enorme incrustada.\p"
	.string "Essa gema, quando próxima a uma Mega Pedra,\n"
	.string "permite que a conexão do treinador com o\l"
	.string "seu Pokémon se manifeste em uma nova\l"
	.string "forma de evolução.\p"
	.string "Embora temporária, essa Megaevolução\n"
	.string "muda a aparência e os atributos do\l"
	.string "Pokémon segurando a Mega Pedra.\p"
	.string "Lembre-se de que as Mega Pedras são\n"
	.string "específicas para cada espécie e nem todo\l"
	.string "Pokémon possui uma Mega forma.\p"
	.string "Para testar isso em batalha, aperte o\n"
	.string "botão START enquanto seleciona o seu\l"
	.string "próximo golpe. O Mega Anel\l"
	.string "deverá brilhar!$"

Route25_SeaCottage_EventScript_PlayerAnsweredNo::
	msgbox Route25_SeaCottage_Text_Collection, MSGBOX_DEFAULT
	release
	end

Route25_SeaCottage_Text_Collection:
	.string "Tudo bem! Que tal dar uma olhada em\n"
    .string "alguns dos meus Pokémon raros no PC?\p"
    .string "Vá em frente, dê uma olhada no meu PC.$"
