DiglettsCave_NorthEntrance_MapScripts::
	.byte 0

DiglettsCave_NorthEntrance_EventScript_Hiker::
	msgbox DiglettsCave_NorthEntrance_RockTunnelPitchBlack, MSGBOX_NPC
	end

DiglettsCave_NorthEntrance_RockTunnelPitchBlack::
    .string "Eu fui no Túnel de Rocha, mas é um breu\n"
    .string "total e muito assustador lá dentro.\p"
    .string "Se eu pudesse fazer um Pokémon usar\n"
    .string "o Flash para iluminar tudo…$"
