SSAnne_2F_Room3_MapScripts::
	.byte 0

SSAnne_2F_Room3_EventScript_Gentleman::
	msgbox SSAnne_2F_Room3_Text_SeenMonsFerryPeople, MSGBOX_NPC
	end

SSAnne_2F_Room3_Text_SeenMonsFerryPeople::
    .string "Ah, sim, já vi alguns Pokémon\n"
    .string "transportando pessoas pela água!$"

SSAnne_2F_Room3_EventScript_OldMan::
	msgbox SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown, MSGBOX_NPC
	end

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown::
    .string "Árvores pequenas podem ser cortadas\n"
    .string "usando o golpe Cortar.\p"
    .string "Mas lembre-se disto!\n"
    .string "Cortar é uma técnica de HM.\p"
    .string "Uma vez aprendida, não é tão fácil\n"
    .string "de esquecer.$"
