Route11_EastEntrance_1F_MapScripts::
	.byte 0

Route11_EastEntrance_1F_EventScript_TopGuard::
	msgbox Route11_EastEntrance_1F_Text_ManInLavenderRatesNames, MSGBOX_NPC
	end

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
    .string "Você não acha difícil inventar nomes\n"
    .string "bons para seus Pokémon?\p"
    .string "Especialmente se você capturou\n"
    .string "um montão deles?\p"
    .string "No Vilarejo de Lavender, há um homem\n"
    .string "que avalia os apelidos dos Pokémon.\p"
    .string "Ele pode até te ajudar a renomear seus\n"
    .string "Pokémon também.$"

Route11_EastEntrance_1F_EventScript_BottomGuard::
	msgbox Route11_EastEntrance_1F_Text_RockTunnelToReachLavender, MSGBOX_NPC
	end

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
    .string "Se o seu objetivo é chegar ao Vilarejo\n"
    .string "de Lavender, atravesse o Túnel de Rocha.\p"
    .string "Você pode chegar ao Túnel de Rocha a\n"
    .string "partir da Cidade de Cerulean.$"
