CeladonCity_House1_MapScripts::
	.byte 0

CeladonCity_House1_EventScript_RocketChief::
	msgbox CeladonCity_House1_Text_SlotsReelInTheDough, MSGBOX_NPC
	end

CeladonCity_House1_Text_SlotsReelInTheDough::
    .string "Hehehe!\p"
    .string "Os caça-níqueis faturam uma grana\n"
    .string "pesada, e como!$"

CeladonCity_House1_EventScript_Rocket1::
	msgbox CeladonCity_House1_Text_ShippedMonsAsSlotPrizes, MSGBOX_NPC
	end

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .string "Chefe!\p"
    .string "Acabamos de enviar mais dois mil\n"
    .string "Bonecos de Pokémon como prêmios\l"
    .string "dos caça-níqueis hoje de novo!\p"
    .string "E também estamos arranjando compradores\n"
    .string "para os Pokémon que sequestramos.$"

CeladonCity_House1_EventScript_Rocket2::
	msgbox CeladonCity_House1_Text_DontTouchGameCornerPoster, MSGBOX_NPC
	end

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .string "Não toque no pôster lá no\n"
    .string "Cassino!\p"
    .string "Não tem nenhum botão secreto atrás dele!$"

CeladonCity_House1_EventScript_PoliceChief::
    msgbox CeladonCity_House1_Text_BustedTheseRockets, MSGBOX_NPC
    end

CeladonCity_House1_Text_BustedTheseRockets::
    .string "Finalmente prendemos os líderes\n"
    .string "desta operação.$"

CeladonCity_House1_EventScript_Police1::
    msgbox CeladonCity_House1_Text_DontStepOnEvidence, MSGBOX_NPC
    end

CeladonCity_House1_Text_DontStepOnEvidence::
    .string "Ei! Cuidado aí, jovem!\n"
    .string "Estamos recolhendo evidências.$"

CeladonCity_House1_EventScript_Police2::
    msgbox CeladonCity_House1_Text_WhoDoesThat, MSGBOX_NPC
    end

CeladonCity_House1_Text_WhoDoesThat::
    .string "Sequestrar e vender Pokémon?\n"
    .string "Que tipo de monstro faz uma coisa dessas?!$"
