import re

ITEMS_TRANSLATION = {
    # Pokébolas
    'Master Ball': 'Mestre Bola',
    'Ultra Ball': 'Ultra Bola',
    'Great Ball': 'Grande Bola',
    'Poké Ball': 'Poké Bola',
    'Safari Ball': 'Bola Safari',
    'Net Ball': 'Bola Rede',
    'Dive Ball': 'Bola Mergulho',
    'Nest Ball': 'Bola Ninho',
    'Repeat Ball': 'Bola Repet.',
    'Timer Ball': 'Bola Tempo',
    'Luxury Ball': 'Bola Luxo',
    'Premier Ball': 'Bola Especial',

    # Remédios e Medicamentos
    'Potion': 'Poção',
    'Antidote': 'Antídoto',
    'Burn Heal': 'Anticura',
    'Ice Heal': 'Descongelante',
    'Awakening': 'Despertador',
    'Parlyz Heal': 'Antiparalisia',
    'Full Restore': 'Restaurador',
    'Max Potion': 'Poção Máxima',
    'Hyper Potion': 'Hiper Poção',
    'Super Potion': 'Super Poção',
    'Full Heal': 'Cura Total',
    'Revive': 'Reviver',
    'Max Revive': 'Reviver Máx.',
    'Fresh Water': 'Água Fresca',
    'Soda Pop': 'Refrigerante',
    'Lemonade': 'Limonada',
    'Moomoo Milk': 'Leite Moomoo',
    'Energypowder': 'Pó de Energia',
    'Energy Root': 'Raiz Energia',
    'Heal Powder': 'Pó de Cura',
    'Revival Herb': 'Erva da Vida',
    'Ether': 'Éter',
    'Max Ether': 'Éter Máximo',
    'Elixir': 'Elixir',
    'Max Elixir': 'Elixir Máx.',
    'Lava Cookie': 'Biscoito Lava',
    'Berry Juice': 'Suco de Fruta',
    'Sacred Ash': 'Cinza Sagr.',

    # Vitaminas
    'HP Up': 'Mais HP',
    'Protein': 'Proteína',
    'Iron': 'Ferro',
    'Carbos': 'Carboidrato',
    'Calcium': 'Cálcio',
    'Rare Candy': 'Doce Raro',
    'PP Up': 'Mais PP',
    'Zinc': 'Zinco',
    'PP Max': 'PP Máximo',

    # Batalha
    'Guard Spec.': 'Defesa Esp.',
    'Dire Hit': 'G. Certeiro',
    'X Attack': 'Ataque X',
    'X Defend': 'Defesa X',
    'X Speed': 'Velocid. X',
    'X Accuracy': 'Precisão X',
    'X Special': 'Especial X',
    'Poké Doll': 'Boneco Poké',
    'Fluffy Tail': 'Cauda Fofa',

    # Repelentes e Campo
    'Super Repel': 'Super Repel.',
    'Max Repel': 'Repel. Máx.',
    'Escape Rope': 'Corda de Fuga',
    'Repel': 'Repelente',

    # Pedras
    'Sun Stone': 'Pedra do Sol',
    'Moon Stone': 'Pedra da Lua',
    'Fire Stone': 'Pedra do Fogo',
    'ThunderStone': 'Pedra Trovão',
    'Water Stone': 'Pedra da Água',
    'Leaf Stone': 'Pedra Folha',

    # Itens segurados e chaves
    'Exp. Share': 'Repartir Exp',
    'Soothe Bell': 'Sino Suave',
    'Amulet Coin': 'Moeda Amuleto',
    'Cleanse Tag': 'Incenso Puro',
    'Smoke Ball': 'Bola Fumaça',
    'Everstone': 'Pedra Eterna',
    'Focus Band': 'Faixa Foco',
    'Lucky Egg': 'Ovo da Sorte',
    'Scope Lens': 'Lente Escopo',
    'Metal Coat': 'Revest.Metal',
    'Leftovers': 'Restos',
    'Dragon Scale': 'EscamaDragão',
    'Light Ball': 'Bola de Luz',
    'Soft Sand': 'Areia Macia',
    'Hard Stone': 'Pedra Dura',
    'Miracle Seed': 'Sem. Milagre',
    'BlackGlasses': 'Óculos Esc.',
    'Black Belt': 'Faixa Preta',
    'Magnet': 'Ímã',
    'Mystic Water': 'Água Mística',
    'Sharp Beak': 'Bico Afiado',
    'Poison Barb': 'Espinho Tóx.',
    'NeverMeltIce': 'Gelo Eterno',
    'Spell Tag': 'Amuleto Feit.',
    'TwistedSpoon': 'Colher Torta',
    'Charcoal': 'Carvão',
    'Dragon Fang': 'Dente Dragão',
    'Silk Scarf': 'Lenço de Seda',
    'Shell Bell': 'Sino Concha',
    'Eviolite': 'Eviolite',

    # Key Items Kanto
    'Old Rod': 'Vara Velha',
    'Good Rod': 'Vara Boa',
    'Super Rod': 'Super Vara',
    'Bicycle': 'Bicicleta',
    'Town Map': 'Mapa Região',
    'Poké Flute': 'Poké Flauta',
    'Secret Key': 'Chave Secreta',
    'Bike Voucher': 'Cupom de Bike',
    'Gold Teeth': 'DentesdeOuro',
    'Old Amber': 'Âmbar Antigo',
    'Card Key': 'Cartão Chave',
    'Lift Key': 'Chave Elevad.',
    'Helix Fossil': 'Fóssil Hélix',
    'Dome Fossil': 'Fóssil Domo',
    'Silph Scope': 'Silph Scope',
    'VS Seeker': 'Buscador VS',
    'TM Case': 'Estojo de TMs',
    'Berry Pouch': 'Bolsa Frutas',
    'Tea': 'Chá',
}

# Dicionario de Golpes (Move Names)
MOVES_TRANSLATION = {
    'Pound': 'Pancada',
    'Karate Chop': 'Golpe Caratê',
    'Double Slap': 'Tapa Duplo',
    'Comet Punch': 'Soco Cometa',
    'Mega Punch': 'Megassoco',
    'Pay Day': 'Dia do Pagam.',
    'Fire Punch': 'Soco de Fogo',
    'Ice Punch': 'Soco de Gelo',
    'Thunder Punch': 'Soco Trovão',
    'ThunderPunch': 'Soco Trovão',
    'Scratch': 'Arranhão',
    'Vise Grip': 'Aperto',
    'Guillotine': 'Guilhotina',
    'Razor Wind': 'Vento Cortant',
    'Swords Dance': 'Dança Espadas',
    'Cut': 'Cortar',
    'Gust': 'Ventania',
    'Wing Attack': 'Ataque de Asa',
    'Whirlwind': 'Redemoinho',
    'Fly': 'Voar',
    'Bind': 'Atar',
    'Slam': 'Pancada Forte',
    'Vine Whip': 'ChicoteVinha',
    'Stomp': 'Pisotear',
    'Double Kick': 'Chute Duplo',
    'Mega Kick': 'Megachute',
    'Jump Kick': 'Chute Pulo',
    'Rolling Kick': 'Chute Girat.',
    'Sand Attack': 'Ataque Areia',
    'Headbutt': 'Cabeçada',
    'Horn Attack': 'Ataque Chifre',
    'Fury Attack': 'Ataque Fúria',
    'Horn Drill': 'Chifre Broca',
    'Tackle': 'Investida',
    'Body Slam': 'Pancada Corp.',
    'Wrap': 'Envolver',
    'Take Down': 'Derrubar',
    'Thrash': 'Agitação',
    'Double-Edge': 'Fio Duplo',
    'Tail Whip': 'Chicote Cauda',
    'Poison Sting': 'Espinho Tóx.',
    'Twineedle': 'Agulha Dupla',
    'Pin Missile': 'Míssil Espin.',
    'Leer': 'Olhar Fixo',
    'Bite': 'Mordida',
    'Growl': 'Rosnado',
    'Roar': 'Rugido',
    'Sing': 'Canto',
    'Supersonic': 'Supersônico',
    'Sonic Boom': 'Estrondo Sôn.',
    'Disable': 'Desabilitar',
    'Acid': 'Ácido',
    'Ember': 'Brasa',
    'Flamethrower': 'Lança-chamas',
    'Mist': 'Névoa',
    'Water Gun': 'Jato d\'Água',
    'Hydro Pump': 'Hidro Bomba',
    'Surf': 'Surf',
    'Ice Beam': 'Raio de Gelo',
    'Blizzard': 'Nevasca',
    'Psybeam': 'RaioPsíquico',
    'Bubble Beam': 'Jato Bolhas',
    'Aurora Beam': 'Raio Aurora',
    'Hyper Beam': 'Hiper Raio',
    'Peck': 'Bicada',
    'Drill Peck': 'Bicada Furad.',
    'Submission': 'Submissão',
    'Low Kick': 'Rasteira',
    'Counter': 'Contra-ataque',
    'Seismic Toss': 'Arremesso',
    'Strength': 'Força',
    'Absorb': 'Absorção',
    'Mega Drain': 'Mega Dreno',
    'Leech Seed': 'SementeDreno',
    'Growth': 'Crescimento',
    'Razor Leaf': 'Folha Navalh',
    'Solar Beam': 'Raio Solar',
    'Poison Powder': 'Pó Venenoso',
    'Stun Spore': 'Pó Paralis.',
    'Sleep Powder': 'Pó do Sono',
    'Petal Dance': 'DançaPétalas',
    'String Shot': 'Tiro de Teia',
    'Dragon Rage': 'Fúria Dragão',
    'Fire Spin': 'Giro de Fogo',
    'Thunder Shock': 'ChoqueTrovão',
    'ThunderShock': 'ChoqueTrovão',
    'Thunderbolt': 'Raio',
    'Thunder Wave': 'Onda Trovão',
    'Thunder': 'Trovão',
    'Rock Throw': 'Lançar Rocha',
    'Earthquake': 'Terremoto',
    'Fissure': 'Fissura',
    'Dig': 'Cavar',
    'Toxic': 'Tóxico',
    'Confusion': 'Confusão',
    'Psychic': 'Psíquico',
    'Hypnosis': 'Hipnose',
    'Meditate': 'Meditação',
    'Agility': 'Agilidade',
    'Quick Attack': 'Ataque Rápido',
    'Rage': 'Fúria',
    'Teleport': 'Teletransp.',
    'Night Shade': 'SombraNoturn',
    'Mimic': 'Mímico',
    'Screech': 'Guincho',
    'Double Team': 'Multiplicar',
    'Recover': 'Recuperar',
    'Harden': 'Endurecer',
    'Minimize': 'Minimizar',
    'Smokescreen': 'CortinaFumaça',
    'Confuse Ray': 'RaioConfusão',
    'Withdraw': 'Retirada',
    'Defense Curl': 'Defesa Enrol',
    'Barrier': 'Barreira',
    'Light Screen': 'Barreira Luz',
    'Haze': 'Neblina',
    'Reflect': 'Reflexo',
    'Focus Energy': 'Foco Energia',
    'Bide': 'Aguentar',
    'Metronome': 'Metrônomo',
    'Mirror Move': 'Mov. Espelho',
    'Self-Destruct': 'Autodestrui.',
    'Egg Bomb': 'Bomba de Ovo',
    'Lick': 'Lambida',
    'Smog': 'Poluição',
    'Sludge': 'Lama',
    'Bone Club': 'Osso Clava',
    'Fire Blast': 'Rajada Fogo',
    'Waterfall': 'Cachoeira',
    'Clamp': 'Concha Prende',
    'Swift': 'Ataque Ágil',
    'Skull Bash': 'Quebra Crânio',
    'Spike Cannon': 'Canhão Espin.',
    'Constrict': 'Constrição',
    'Amnesia': 'Amnésia',
    'Kinesis': 'Cinese',
    'Soft-Boiled': 'Ovo Fervido',
    'High Jump Kick': 'Super Salto',
    'Hi Jump Kick': 'Super Salto',
    'Glare': 'Olhar Intim.',
    'Dream Eater': 'ComedorSonho',
    'Poison Gas': 'Gás Venenoso',
    'Barrage': 'Bombardeio',
    'Leech Life': 'Chupa Sangue',
    'Lovely Kiss': 'Beijo Doce',
    'Sky Attack': 'Ataque do Céu',
    'Transform': 'Transformar',
    'Bubble': 'Bolha',
    'Dizzy Punch': 'Soco Tonto',
    'Spore': 'Esporos',
    'Flash': 'Clarão',
    'Psywave': 'OndaPsíquica',
    'Splash': 'Borrifar',
    'Acid Armor': 'ArmaduraÁcid',
    'Crabhammer': 'Martelo Car.',
    'Explosion': 'Explosão',
    'Fury Swipes': 'Garras Fúria',
    'Bonemerang': 'Ossomerangue',
    'Rest': 'Descanso',
    'Rock Slide': 'Deslizamento',
    'Hyper Fang': 'Hiper Presa',
    'Sharpen': 'Afiar',
    'Conversion': 'Conversão',
    'Tri Attack': 'Ataque Triplo',
    'Super Fang': 'Super Presa',
    'Slash': 'Talho',
    'Substitute': 'Substituto',
    'Struggle': 'Debater',
}

# Dicionario de Habilidades (Abilities)
ABILITIES_TRANSLATION = {
    'Stench': 'Mau Cheiro',
    'Drizzle': 'Garoa',
    'Speed Boost': 'Impulso',
    'Battle Armor': 'ArmaduraBat.',
    'Sturdy': 'Robustez',
    'Damp': 'Umidade',
    'Limber': 'Flexível',
    'Sand Veil': 'Véu de Areia',
    'Static': 'Estática',
    'Volt Absorb': 'Absorve Elet',
    'Water Absorb': 'Absorve Água',
    'Oblivious': 'Alheio',
    'Cloud Nine': 'Tempo Limpo',
    'Compound Eyes': 'Olhos Compost',
    'CompoundEyes': 'Olhos Compost',
    'Insomnia': 'Insônia',
    'Color Change': 'Muda de Cor',
    'Immunity': 'Imunidade',
    'Flash Fire': 'Fogo Rápido',
    'Shield Dust': 'Pó Escudo',
    'Own Tempo': 'Ritmo Próprio',
    'Suction Cups': 'Ventosas',
    'Intimidate': 'Intimidação',
    'Shadow Tag': 'Sombra Presa',
    'Rough Skin': 'Pele Áspera',
    'Wonder Guard': 'Guarda Mágic',
    'Levitate': 'Levitação',
    'Effect Spore': 'Esporo Efeit',
    'Synchronize': 'Sincronia',
    'Clear Body': 'Corpo Limpo',
    'Natural Cure': 'Cura Natural',
    'Lightning Rod': 'Para-raios',
    'LightningRod': 'Para-raios',
    'Serene Grace': 'Graça Serena',
    'Swift Swim': 'Nado Rápido',
    'Chlorophyll': 'Clorofila',
    'Illuminate': 'Iluminar',
    'Trace': 'Cópia',
    'Huge Power': 'Super Força',
    'Poison Point': 'Ponto Tóxico',
    'Inner Focus': 'Foco Interno',
    'Magma Armor': 'ArmaduraMag.',
    'Water Veil': 'Véu de Água',
    'Magnet Pull': 'Ímã Atração',
    'Soundproof': 'À Prova Som',
    'Rain Dish': 'Prato Chuva',
    'Sand Stream': 'Temp. Areia',
    'Pressure': 'Pressão',
    'Thick Fat': 'Gordura',
    'Early Bird': 'Madrugador',
    'Flame Body': 'Corpo Chamas',
    'Run Away': 'Fuga',
    'Keen Eye': 'Olhar Atento',
    'Hyper Cutter': 'Hiper Cortad',
    'Pickup': 'Coleta',
    'Truant': 'Preguiça',
    'Hustle': 'Agitação',
    'Cute Charm': 'Encanto',
    'Plus': 'Mais',
    'Minus': 'Menos',
    'Forecast': 'Previsão',
    'Overgrow': 'Supercrescer',
    'Blaze': 'Chama',
    'Torrent': 'Torrente',
    'Swarm': 'Enxame',
    'Rock Head': 'Cabeça Rocha',
    'Drought': 'Seca',
    'Arena Trap': 'Armadilha',
    'Vital Spirit': 'Espír. Vital',
    'White Smoke': 'Fumaça Branc',
    'Pure Power': 'Poder Puro',
    'Shell Armor': 'Armad.Casco',
    'Air Lock': 'Eclusa de Ar',
}

def translate_items():
    with open('src/data/items.h', 'r', encoding='utf-8') as f:
        content = f.read()

    count = 0
    for en, pt in ITEMS_TRANSLATION.items():
        pattern = rf'(\.name\s*=\s*_\("){re.escape(en)}("\))'
        if re.search(pattern, content):
            content = re.sub(pattern, rf'\g<1>{pt}\g<2>', content)
            count += 1

    with open('src/data/items.h', 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Itens traduzidos: {count}")

def translate_moves():
    with open('src/data/text/move_names.h', 'r', encoding='utf-8') as f:
        content = f.read()

    # Traduz apenas na primeira tabela (B_EXPANDED_MOVE_NAMES == TRUE, antes de #else)
    parts = content.split('#else')
    part_expanded = parts[0]

    count = 0
    for en, pt in MOVES_TRANSLATION.items():
        pattern = rf'(_\("){re.escape(en)}("\))'
        matches = len(re.findall(pattern, part_expanded))
        if matches > 0:
            part_expanded = re.sub(pattern, rf'\g<1>{pt}\g<2>', part_expanded)
            count += matches

    parts[0] = part_expanded
    content = '#else'.join(parts)

    with open('src/data/text/move_names.h', 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Golpes traduzidos: {count}")

def translate_abilities():
    with open('src/data/text/abilities.h', 'r', encoding='utf-8') as f:
        content = f.read()

    count = 0
    for en, pt in ABILITIES_TRANSLATION.items():
        pattern = rf'(_\("){re.escape(en)}("\))'
        matches = len(re.findall(pattern, content))
        if matches > 0:
            content = re.sub(pattern, rf'\g<1>{pt}\g<2>', content)
            count += matches

    with open('src/data/text/abilities.h', 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Habilidades traduzidas: {count}")

if __name__ == '__main__':
    translate_items()
    translate_moves()
    translate_abilities()
