.set LOCALID_OAK, 1
.set LOCALID_PIKACHU, 2
.set LOCALID_FUGITIVE, 7

Route1_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route1_OnTransition
	map_script MAP_SCRIPT_ON_RESUME, Route1_OnResume
	.byte 0

Route1_OnTransition:
	call Common_EventScript_GetDayOrNight
	end

Route1_OnResume:
	removeobject LOCALID_PIKACHU
	call Common_EventScript_GetDayOrNight
	end

Route1_EventScript_OakAppears1::
	lockall
	addobject LOCALID_OAK
	applymovement LOCALID_OAK, Movement_OakAppears
	waitmovement 1
	msgbox Route1_Text_OakDontGoOut, MSGBOX_DEFAULT
	playse SE_PIN
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_Delay48
	waitmovement 0
	applymovement LOCALID_OAK, Movement_OakApproaches1
	waitmovement 1
	msgbox Route1_Text_OakGrassUnsafe, MSGBOX_DEFAULT
	closemessage
	addobject LOCALID_PIKACHU
	applymovement LOCALID_PIKACHU, Movement_PikachuApproaches1
	waitmovement 2
	goto Route1_EventScript_PikachuEncounter
	releaseall
	end

Route1_EventScript_OakAppears2::
	lockall
	addobject LOCALID_OAK
	applymovement LOCALID_OAK, Movement_OakAppears
	waitmovement 1
	msgbox Route1_Text_OakDontGoOut, MSGBOX_DEFAULT
	playse SE_PIN
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_Delay48
	waitmovement 0
	applymovement LOCALID_OAK, Movement_OakApproaches2
	waitmovement 1
	msgbox Route1_Text_OakGrassUnsafe, MSGBOX_DEFAULT
	closemessage
	addobject LOCALID_PIKACHU
	applymovement LOCALID_PIKACHU, Movement_PikachuApproaches2
	waitmovement 2
	goto Route1_EventScript_PikachuEncounter
	releaseall
	end

Movement_OakAppears:
	walk_down
	step_end

Route1_Text_OakDontGoOut::
    .string "Carvalho: Ei! Espere!\n"
    .string "Não venha por aqui!$"


Movement_OakApproaches1:
	walk_down
	walk_down
	walk_down
	step_end

Movement_OakApproaches2:
	walk_right
	walk_down
	walk_down
	walk_down
	step_end

Route1_Text_OakGrassUnsafe::
    .string "Carvalho: É perigoso!\n"
    .string "Pokémon selvagens vivem na grama alta!\p"
    .string "Você precisa do seu próprio Pokémon\n"
    .string "para a sua proteção.$"

Movement_PikachuApproaches1:
	walk_down
	walk_down
	walk_down
	walk_down
	step_end

Movement_PikachuApproaches2:
	walk_left
	walk_down
	walk_down
	walk_down
	walk_down
	step_end

Route1_EventScript_PikachuEncounter::
	turnobject LOCALID_OAK, DIR_NORTH
	playse SE_PIN
	applymovement LOCALID_OAK, Common_Movement_ExclamationMark
	waitmovement 1
	applymovement LOCALID_OAK, Common_Movement_Delay48
	waitmovement 1
	special SavePlayerParty
	special PutZigzagoonInPlayerParty
	special StartWallyTutorialBattle
	setflag FLAG_HIDE_PIKACHU_ROUTE1
	waitstate
	special LoadPlayerParty
	turnobject LOCALID_OAK, DIR_SOUTH
	msgbox Route1_Text_ThatWasClose, MSGBOX_DEFAULT
	setvar VAR_ADVENTURE_BEGINS, 2
	fadescreen FADE_TO_BLACK
	setflag FLAG_HIDE_MAP_NAME_POPUP
	clearflag FLAG_HIDE_OAK_IN_LAB
	setvar VAR_OAK_LAB_STATE, 1
	warp MAP_PALLET_TOWN_PROFESSOR_OAKS_LAB, 6, 5
	waitstate
	return

Route1_Text_ThatWasClose::
    .string "Carvalho: Essa foi por pouco!\n"
    .string "Mas que coisa estranha...\p"
    .string "Não é comum ver Pikachu\n"
    .string "por esta área...\p"
    .string "Vamos voltar para o meu laboratório!$"

Route1_EventScript_MartClerk::
	lock
	faceplayer
	goto_if_set FLAG_GOT_POTION_ON_ROUTE_1, Route1_EventScript_AlreadyGotPotion
	msgbox Route1_Text_WorkAtPokeMartTakeSample, MSGBOX_DEFAULT
	checkitemspace ITEM_POTION, 1
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_BagIsFull
	giveitem ITEM_POTION, 1
	setflag FLAG_GOT_POTION_ON_ROUTE_1
	release
	end

Route1_Text_WorkAtPokeMartTakeSample::
    .string "Olá!\n"
    .string "Eu trabalho no Pokémon Mart.\p"
    .string "É parte de uma rede conveniente que\n"
    .string "vende todo tipo de item útil.\p"
    .string "Por favor, venha nos visitar em Viridian City.\p"
    .string "Já sei, vou te dar uma amostra.\n"
    .string "Aqui está!$"

Route1_EventScript_AlreadyGotPotion::
	msgbox Route1_Text_ComeSeeUsIfYouNeedPokeBalls
	release
	end

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Venha nos visitar se precisar de\n"
    .string "Pokébolas para capturar Pokémon.$"

Route1_EventScript_Boy::
	msgbox Route1_Text_CanJumpFromLedges, MSGBOX_NPC
	end

Route1_Text_CanJumpFromLedges::
    .string "Viu aqueles desníveis pelo caminho?\p"
    .string "Dá um friozinho na barriga, mas dá para\n"
    .string "pular por eles.\p"
    .string "Assim você consegue voltar para Pallet Town\n"
    .string "bem mais rápido.$"

Route1_EventScript_RouteSign::
	msgbox Route1_Text_RouteSign, MSGBOX_SIGN
	end

Route1_Text_RouteSign::
    .string "Rota 1\n"
    .string "Pallet Town - Viridian City$"

Route1_RocketFugitive::
	trainerbattle_single TRAINER_FUGITIVE_F, RocketFugitive_Text_Intro, RocketFugitive_Text_Defeat
	msgbox RocketFugitive_Text_PostBattle, MSGBOX_AUTOCLOSE
	setflag FLAG_ROCKET_FUGITIVE_CAPTURED
	fadescreen FADE_TO_BLACK
	playse SE_FLEE
	removeobject LOCALID_FUGITIVE
	waitse
	fadescreen FADE_FROM_BLACK
	end

Route1_EventScript_Pidgeot::
	lock
	faceplayer
    playmoncry SPECIES_PIDGEOT, CRY_MODE_ENCOUNTER
    waitmoncry
    delay 20
    goto_if_set FLAG_DEFEATED_MURAMASA, Route1_EventScript_PidgeotDefeated
	msgbox Route1_Text_Pidgeot MSGBOX_DEFAULT
	release
	end

Route1_Text_Pidgeot:
	.string "Pidgeot parece cansado, mas focado\n"
	.string "em voar o mais rápido possível.$"

Route1_EventScript_CoolTrainerMura::
	lock
	faceplayer
	goto_if_set FLAG_DEFEATED_MURAMASA, Route1_EventScript_MegaHintPidgeot
	trainerbattle_single TRAINER_POKEMON_COOLTRAINER_MURA, Route1_Text_MuraIntro, Route1_Text_MuraDefeat
	setflag FLAG_DEFEATED_MURAMASA
	msgbox Route1_Text_MuraPostBattle MSGBOX_AUTOCLOSE
	release
	end

Route1_Text_MuraIntro:
	.string "Ei, garoto! Viu algum Pokémon brilhante\p"
	.string "por aqui? Estou procurando um Pidgey.$"

Route1_Text_MuraDefeat:
	.string "Espera aí, tempo!$"

Route1_Text_MuraPostBattle:
	.string "Estamos aqui o dia todo tentando\n"
	.string "encontrar Pokémon brilhantes!$"

Route1_EventScript_MegaHintPidgeot::    
    goto_if_set FLAG_GOT_PIDGEOTITE, Route1_EventScript_MuraDefeated
    msgbox Route1_Text_PidgeotMegaHint MSGBOX_DEFAULT
    waitmessage
    release
    end
    
Route1_Text_PidgeotMegaHint:
    .string "Não achei nenhum Pokémon brilhante na\n"
	.string "Rota 2, mas achei outras coisas boas!$"

Route1_EventScript_MuraDefeated::
    msgbox MuraDefeated_Text MSGBOX_DEFAULT
	release
	end

MuraDefeated_Text:	
	.string "Um dia eu terei um Pidgeot brilhante!\n"
	.string "Vou ficar tão maneiro voando nele.$"

Route1_EventScript_PidgeotDefeated::
	msgbox PidgeotDefeated MSGBOX_DEFAULT
	release
	end

PidgeotDefeated:	
	.string "Pidgeot está ainda mais determinado\n"
	.string "do que antes a ser o melhor.$"
