FuchsiaCity_SafariZone_Office_MapScripts::
	.byte 0

FuchsiaCity_SafariZone_Office_EventScript_Worker1::
	msgbox FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .string "Apelidamos o Guarda de\n"
    .string "“Slowpoke”.\p"
    .string "Sabe, ele tem aquele olhar vago\n"
    .string "igual ao de um Slowpoke.$"

FuchsiaCity_SafariZone_Office_EventScript_Worker2::
	msgbox FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
    .string "O Guarda Slowpoke tem muito\n"
    .string "conhecimento sobre Pokémon.\p"
    .string "Ele até tem fósseis de Pokémon\n"
    .string "raros e extintos.$"

FuchsiaCity_SafariZone_Office_EventScript_Worker3::
	msgbox FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .string "O Guarda Slowpoke apareceu por aqui,\n"
    .string "mas não consegui entender nada.\p"
    .string "Acho que ele está com problemas na fala!$"

FuchsiaCity_SafariZone_Office_EventScript_Worker4::
	msgbox FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "O Guarda Slowpoke está fazendo uma\n"
    .string "campanha promocional agora mesmo.\p"
    .string "Tente chegar ao canto mais distante\n"
    .string "da Zona do Safári.\p"
    .string "Se você conseguir, vai ganhar um\n"
    .string "prêmio muito conveniente.$"
