DiglettsCave_SouthEntrance_MapScripts::
	.byte 0

DiglettsCave_SouthEntrance_EventScript_OldMan::
	msgbox DiglettsCave_SouthEntrance_Text_DiglettDugThisTunnel, MSGBOX_NPC
	end

DiglettsCave_SouthEntrance_Text_DiglettDugThisTunnel::
    .string "Ora, vejam só que surpresa!\n"
    .string "Diglett cavou este túnel enorme!\p"
    .string "Ele vai direto para a Cidade de Viridian,\n"
    .string "foi o que me disseram.$"
