FuchsiaCity_SafariZone_Entrance_MapScripts::
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FuchsiaCity_SafariZone_Entrance_OnFrame
	.byte 0

FuchsiaCity_SafariZone_Entrance_OnFrame:
	map_script_2 VAR_SAFARI_ZONE_STATE, 1, FuchsiaCity_SafariZone_Entrance_EventScript_ExitSafariZone
	.2byte 0

FuchsiaCity_SafariZone_Entrance_EventScript_ExitSafariZone::
	lockall
	applymovement OBJ_EVENT_ID_PLAYER, FuchsiaCity_SafariZone_Entrance_Movement_ExitSafariZone
	waitmovement 0
	setvar VAR_SAFARI_ZONE_STATE, 0
	releaseall
	end

FuchsiaCity_SafariZone_Entrance_Movement_ExitSafariZone:
	walk_down
	walk_down
	walk_down
	step_end

FuchsiaCity_SafariZone_Entrance_EventScript_WelcomeAttendant::
	lock
	faceplayer
	msgbox FuchsiaCity_SafariZone_Entrance_Text_WelcomeFirstTime, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, FuchsiaCity_SafariZone_Entrance_EventScript_FirstTimeInfo
	msgbox FuchsiaCity_SafariZone_Entrance_Text_ComeInAndEnjoy, MSGBOX_DEFAULT
	release
	end

FuchsiaCity_SafariZone_Entrance_EventScript_InfoAttendant::
	msgbox FuchsiaCity_SafariZone_Entrance_Text_TrainerTip, MSGBOX_SIGN
	end

FuchsiaCity_SafariZone_Entrance_Text_TrainerTip:
	.string "Aqui vai uma dica!\p"
	.string "Jogue {POKEBLOCK}s nos Pokémon selvagens para\n"
	.string "torná-los menos propensos a fugir.$"

FuchsiaCity_SafariZone_Entrance_Text_WelcomeFirstTime:
	.string "Boas-vindas à Zona do Safári!\n"
	.string "É a sua primeira vez aqui?$"

FuchsiaCity_SafariZone_Entrance_Text_ComeInAndEnjoy:
	.string "Entre e aproveite a Zona do Safári!$"

FuchsiaCity_SafariZone_Entrance_EventScript_FirstTimeInfo::
	msgbox FuchsiaCity_SafariZone_Entrance_Text_FirstTimeInfo, MSGBOX_DEFAULT
	release
	end

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeInfo:
	.string "Ao entrar na Zona do Safári, você\n"
	.string "começa com 30 Bolas Safári para\l"
	.string "capturar Pokémon.\p"
	.string "O Jogo do Safári termina quando suas\n"
	.string "Bolas Safári acabarem ou quando você\l"
	.string "der 500 passos.\p"
	.string "Entre e aproveite a Zona do Safári!$"

FuchsiaCity_SafariZone_Entrance_EventScript_EntranceCounterTriggerLeft::
	lockall
	applymovement OBJ_EVENT_ID_PLAYER, Movement_ApproachCounterLeft
	waitmovement 0
	goto FuchsiaCity_SafariZone_Entrance_EventScript_EntranceCounter
	end

Movement_ApproachCounterLeft::
	walk_right
	walk_right
	step_end

FuchsiaCity_SafariZone_Entrance_EventScript_EntranceCounterTriggerMid::
	lockall
	applymovement OBJ_EVENT_ID_PLAYER, Movement_ApproachCounterMid
	waitmovement 0
	goto FuchsiaCity_SafariZone_Entrance_EventScript_EntranceCounter
	end

Movement_ApproachCounterMid::
	walk_right
	step_end

FuchsiaCity_SafariZone_Entrance_EventScript_EntranceCounter::
	lockall
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	showmoneybox 0, 0
	msgbox FuchsiaCity_SafariZone_Entrance_Text_WouldYouLikeToPlay, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, FuchsiaCity_SafariZone_Entrance_EventScript_TryEnterSafariZone
	msgbox FuchsiaCity_SafariZone_Entrance_Text_PlayAnotherTime, MSGBOX_DEFAULT
	goto FuchsiaCity_SafariZone_Entrance_EventScript_MovePlayerBackFromCounter
	end

FuchsiaCity_SafariZone_Entrance_Text_WouldYouLikeToPlay:
	.string "Boas-vindas à Zona do Safári!\p"
	.string "Capture o quanto puder por apenas ¥500!\n"
	.string "Gostaria de participar do Jogo do Safári?$"

FuchsiaCity_SafariZone_Entrance_Text_PlayAnotherTime:
	.string "Certo.\n"
	.string "Por favor, volte em outra ocasião!$"

FuchsiaCity_SafariZone_Entrance_EventScript_TryEnterSafariZone::
	call FuchsiaCity_SafariZone_Entrance_EventScript_CheckHasRoomForPokemon
	checkmoney 500
	goto_if_eq VAR_RESULT, 0, FuchsiaCity_SafariZone_Entrance_EventScript_NotEnoughMoney
	playse SE_SHOP
	msgbox FuchsiaCity_SafariZone_Entrance_Text_ThatWillBe500Please, MSGBOX_DEFAULT
	removemoney 500
	updatemoneybox
	msgbox FuchsiaCity_SafariZone_Entrance_Text_HereAreYourSafariBalls, MSGBOX_DEFAULT
	playfanfare MUS_OBTAIN_ITEM
	message FuchsiaCity_SafariZone_Entrance_Text_Received30SafariBalls
	waitfanfare
	msgbox FuchsiaCity_SafariZone_Entrance_Text_PleaseEnjoyYourself, MSGBOX_DEFAULT
	closemessage
	hidemoneybox
	applymovement OBJ_EVENT_ID_PLAYER, FuchsiaCity_SafariZone_Entrance_Movement_EnterSafariZone
	waitmovement 0
	special EnterSafariMode
	setvar VAR_SAFARI_ZONE_STATE, 2
	warp MAP_SAFARI_ZONE_CENTER, 26, 30
	waitstate
	end

FuchsiaCity_SafariZone_Entrance_Text_ThatWillBe500Please:
	.string "Serão ¥500, por favor.$"

FuchsiaCity_SafariZone_Entrance_Text_HereAreYourSafariBalls:
	.string "Aqui estão as suas Bolas Safári.$"

FuchsiaCity_SafariZone_Entrance_Text_Received30SafariBalls:
    .string "{PLAYER} recebeu 30 Bolas Safári\n"
    .string "do atendente.$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseEnjoyYourself:
    .string "Avisaremos pelo alto-falante quando o\n"
    .string "seu tempo ou as Bolas Safári acabarem.\p"
    .string "Bem, desejo a você muita boa sorte!$"

FuchsiaCity_SafariZone_Entrance_Movement_EnterSafariZone:
	walk_left
	walk_up
	walk_up
	delay_16
	step_end

FuchsiaCity_SafariZone_Entrance_EventScript_CheckHasRoomForPokemon::
	getpartysize
	goto_if_ne VAR_RESULT, PARTY_SIZE, Common_EventScript_Return
	specialvar VAR_RESULT, ScriptCheckFreePokemonStorageSpace
	goto_if_eq VAR_RESULT, 1, Common_EventScript_Return
	msgbox FuchsiaCity_SafariZone_Entrance_Text_PCIsFull, MSGBOX_DEFAULT
	goto FuchsiaCity_SafariZone_Entrance_EventScript_MovePlayerBackFromCounter
	end

FuchsiaCity_SafariZone_Entrance_Text_PCIsFull:
	.string "Com licença!\n"
	.string "Sua Caixa do PC está cheia.$"

FuchsiaCity_SafariZone_Entrance_EventScript_NotEnoughMoney::
	msgbox FuchsiaCity_SafariZone_Entrance_Text_NotEnoughMoney, MSGBOX_DEFAULT
	goto FuchsiaCity_SafariZone_Entrance_EventScript_MovePlayerBackFromCounter
	end

FuchsiaCity_SafariZone_Entrance_Text_NotEnoughMoney:
	.string "Você não tem dinheiro suficiente.\n"
	.string "Desculpe.$"

FuchsiaCity_SafariZone_Entrance_EventScript_MovePlayerBackFromCounter::
	closemessage
	hidemoneybox
	applymovement OBJ_EVENT_ID_PLAYER, FuchsiaCity_SafariZone_Entrance_Movement_BackAwayFromCounter
	waitmovement 0
	releaseall
	end

FuchsiaCity_SafariZone_Entrance_Movement_BackAwayFromCounter:
	walk_down
	step_end



FuchsiaCity_SafariZone_Entrance_EventScript_ExitCounterTriggerLeft::
	lockall
	applymovement OBJ_EVENT_ID_PLAYER, Movement_ApproachCounterLeft
	waitmovement 0
	goto FuchsiaCity_SafariZone_Entrance_EventScript_ExitCounter
	end

FuchsiaCity_SafariZone_Entrance_EventScript_ExitCounterTriggerMid::
	lockall
	applymovement OBJ_EVENT_ID_PLAYER, Movement_ApproachCounterMid
	waitmovement 0
	goto FuchsiaCity_SafariZone_Entrance_EventScript_ExitCounter
	end

FuchsiaCity_SafariZone_Entrance_EventScript_ExitCounter::
	lockall
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	msgbox FuchsiaCity_SafariZone_Entrance_Text_StillHaveTimeExit, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, FuchsiaCity_SafariZone_Entrance_EventScript_Exit
	msgbox FuchsiaCity_SafariZone_Entrance_Text_EnjoyTheRestOfYourAdventure, MSGBOX_DEFAULT
	closemessage
	applymovement OBJ_EVENT_ID_PLAYER, FuchsiaCity_SafariZone_Entrance_Movement_EnterSafariZone
	waitmovement 0
	warp MAP_SAFARI_ZONE_CENTER, 26, 30
	waitstate
	end

FuchsiaCity_SafariZone_Entrance_Text_EnjoyTheRestOfYourAdventure:
	.string "Por favor, aproveite o restante da\n"
	.string "sua aventura selvagem!$"

FuchsiaCity_SafariZone_Entrance_Text_StillHaveTimeExit:
    .string "Você deseja sair da Zona do Safári\n"
    .string "antes da hora?$"

FuchsiaCity_SafariZone_Entrance_EventScript_Exit::
	msgbox FuchsiaCity_SafariZone_Entrance_Text_ExitEarlyThankYouForPlaying, MSGBOX_DEFAULT
	setvar VAR_SAFARI_ZONE_STATE, 0
	special ExitSafariMode
	goto FuchsiaCity_SafariZone_Entrance_EventScript_MovePlayerBackFromCounter
	end

FuchsiaCity_SafariZone_Entrance_Text_ExitEarlyThankYouForPlaying:
    .string "Por favor, devolva as Bolas Safári\n"
    .string "que ainda tiver com você.$"
