name: Build ROM

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout agbcc
        uses: actions/checkout@v4
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libpng-dev

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Compile ROM
        run: make -j$(nproc) all

      - name: Upload GBA ROM
        uses: actions/upload-artifact@v4
        with:
          name: Pokemon_Kanto_Johto_ROM
          path: |
            Pokemon_Kanto_Johto.gba
            pokeClassic.gba
          if-no-files-found: error
